### ISSUE TITLE
QA-Landing Page: Header area photo

### ISSUE THREAD

**Issue by cherylhjli** [greatislander/platform.coop#20]
Should be full bleed and stretch to the edge, like so:
![Screen Shot 2019-04-18 at 1 36 49 PM](https://user-images.githubusercontent.com/9353905/56380025-0fab5a00-61df-11e9-82ef-19ec9af0572a.png)

**Comment by greatislander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Landing page hero image/text adjustments](https://trello.com/c/ioNAz7bG/71-landing-page-hero-image-text-adjustments)
