### ISSUE TITLE
QA-Landing Page: Header area background colour

### ISSUE THREAD

**Issue by cherylhjli** [greatislander/platform.coop#21]
The area behind "A hub that helps you..." is #F0EFEF in the designs, like so:
![Screen Shot 2019-04-18 at 1 36 49 PM](https://user-images.githubusercontent.com/9353905/56380089-39648100-61df-11e9-9a52-e0f1b7d4256c.png)

**Comment by greatislander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Landing page hero image/text adjustments](https://trello.com/c/ioNAz7bG/71-landing-page-hero-image-text-adjustments)
