### ISSUE TITLE
QA-Landing Page: Donate spacing on desktop

### ISSUE THREAD

**Issue by cherylhjli** [greatislander/platform.coop#23]
The spacing between "donate" header and the body text should be the same amount as the spacing between the body text and the "donate now" button.
![Screen Shot 2019-04-18 at 1 39 44 PM](https://user-images.githubusercontent.com/9353905/56380272-c27bb800-61df-11e9-8e83-b3fd13b9380a.png)

**Comment by greatislander** [comment]
Fixed in https://github.com/greatislander/platform.coop/commit/24e3e790c4121a0571ff9411f085b53b4919b391.
