### ISSUE TITLE
QA-Vision & principles: No vertical red line leading below the fold

### ISSUE THREAD

**Issue by cherylhjli** [greatislander/platform.coop#41]
<img width="67" alt="Screen Shot 2019-05-07 at 10 23 55 AM" src="https://user-images.githubusercontent.com/9353905/57307253-3e1ba700-70b2-11e9-8255-5a7aa34a423a.png">

This little thing!

**Comment by greatislander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QA: add decorative line leading below fold](https://trello.com/c/jUcOAF29/78-qa-add-decorative-line-leading-below-fold)
