### ISSUE TITLE
QA-Footer: Styling

### ISSUE THREAD

**Issue by cherylhjli** [greatislander/platform.coop#46]
**Padding**

Reduce the space on the top and bottom around the logo in the footer by around half

Current website:
![Screen Shot 2019-05-07 at 10 46 25 AM](https://user-images.githubusercontent.com/9353905/57309158-956f4680-70b5-11e9-8ffa-06b0c810bf07.png)

Designs:
<img width="290" alt="Screen Shot 2019-05-07 at 10 46 37 AM" src="https://user-images.githubusercontent.com/9353905/57309171-9a33fa80-70b5-11e9-86ec-f786f2b4549e.png">

**Typeface**

Current website uses noto serif
Designs use noto sans

**Comment by greatislander** [comment]
I reduced the top and bottom margin on the logo. Worth noting that the focus state includes a bottom border, so I can't cut it in half as requested (we could come up with an alternative focus state if you want).

![Footer with logo in focus state.](https://user-images.githubusercontent.com/605361/57320926-7c2ac200-70d6-11e9-85b2-1d2997963a63.png)
