### ISSUE TITLE
QA-Styling: Links

### ISSUE THREAD

**Issue by cherylhjli** [greatislander/platform.coop#50]
Links that are not breadcrumbs should be noto sans instead of noto serif, in semibold.

I know you're not done putting in the icons yet, but I thought I'd point this part out just in case:
![Screen Shot 2019-05-07 at 11 30 08 AM](https://user-images.githubusercontent.com/9353905/57312484-a7ec7e80-70bb-11e9-93b0-516e07a7678c.png)

**Comment by greatislander** [comment]
Fixed typeface. TODO: icons.

**Comment by greatislander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QA: restore icons to reusable social links block](https://trello.com/c/jfa4QNfx/79-qa-restore-icons-to-reusable-social-links-block)

**Comment by cherylhjli** [comment]
Sorry I know this is _super_ nitpicky, a few things..

<img width="463" alt="Screen Shot 2019-05-09 at 11 02 13 AM" src="https://user-images.githubusercontent.com/9353905/57464045-021b4a00-724a-11e9-83eb-aee1c9fb88ea.png">

my bad - I should've been more specific about the links being noto serif semibold weight, not just regular. Could they be semibold as well? :) Here, as well as for the info@platform.coop part on the same page.

Also, is there a way for that little line between the icon and the first letter to not be there?

Sorry & thanks!!
