### ISSUE TITLE
QA-Benefits-Co-op member owner: Header image

### ISSUE THREAD

**Issue by cherylhjli** [greatislander/platform.coop#56]
It seems that in the current website, it takes up a column or two more than it does in the designs - causing the heading to be cut off in awkward places

![Screen Shot 2019-05-07 at 3 47 38 PM](https://user-images.githubusercontent.com/9353905/57328545-b2b90a80-70df-11e9-9b75-4402c9275d99.png)

![Screen Shot 2019-05-07 at 3 47 31 PM](https://user-images.githubusercontent.com/9353905/57328546-b2b90a80-70df-11e9-9547-33c317a7998f.png)

**Comment by greatislander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Page template: how platform co-ops can benefit you](https://trello.com/c/2M2Lfgyb/67-page-template-how-platform-co-ops-can-benefit-you)
