### ISSUE TITLE
QA-Benefits-Co-op member owner: Header

### ISSUE THREAD

**Issue by cherylhjli** [greatislander/platform.coop#58]
A few small changes:

- The persona name (in this case "co-op member owners" should be in #16605D
- The offset colour for the header image shoudl be #FCC2A7

**Comment by greatislander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Page template: how platform co-ops can benefit you](https://trello.com/c/2M2Lfgyb/67-page-template-how-platform-co-ops-can-benefit-you)

**Comment by greatislander** [comment]
@cherylhjli #FCC2A7 isn't one of the named colours in the palette; I'm assuming you want that to be #FDC2A7 (pale red)? Or should pale red be redefined to #FCC2A7? Or, should we add another colour to the palette?

**Comment by cherylhjli** [comment]
#FFA47A is slightly darker than #FDC2A7, so if you could add one that would be great :)

**Comment by cherylhjli** [comment]
Also, I noticed that the header image in the website is still a bit bigger than the designs - is it possible to make it a smidge smaller?
