### ISSUE TITLE
QA-Benefits-Index: Spacing between image and text

### ISSUE THREAD

**Issue by cherylhjli** [greatislander/platform.coop#60]
Just a taaad bit more space between the image and text please?

![Screen Shot 2019-05-07 at 3 53 56 PM](https://user-images.githubusercontent.com/9353905/57328773-55718900-70e0-11e9-9579-a52fc98535c1.png)

**Comment by greatislander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Page template: how platform co-ops can benefit you](https://trello.com/c/2M2Lfgyb/67-page-template-how-platform-co-ops-can-benefit-you)
