### ISSUE TITLE
QA-Style: Donate spacing

### ISSUE THREAD

**Issue by cherylhjli** [greatislander/platform.coop#61]
I guess this must've happened due to the faulty spacing specs I gave you, but could you decrease the space between "donate" and the body copy by around half?

Thanks!

Currently on website:
![Screen Shot 2019-05-07 at 3 56 07 PM](https://user-images.githubusercontent.com/9353905/57328988-d597ee80-70e0-11e9-9ed9-a185f9050cde.png)

Designs:
![Screen Shot 2019-05-07 at 3 56 13 PM](https://user-images.githubusercontent.com/9353905/57329000-dc266600-70e0-11e9-9489-fcb8a5bb3f38.png)

**Comment by greatislander** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QA: Donate spacing](https://trello.com/c/cz1qbSlB/80-qa-donate-spacing)
