### ISSUE TITLE
QA-style: Dark teal

### ISSUE THREAD

**Issue by cherylhjli** [greatislander/platform.coop#73]
I noticed a few variations of the dark teal around the site - that probably comes from having 2 extremely similar teals in the colour palette.
To make it easier, can we just make all #1D7C79 into #16605D? The latter is AAA compliant whereas the former is only AA. 
Thanks!

**Comment by greatislander** [comment]
Buttons should hover to lighter teal (reverse).

**Comment by cherylhjli** [comment]
only thing I found that wasn't dark teal are the headers on the "contact us" page, and the teal button backgrounds!
